# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpertWorkBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'lottie-ios'
  pod 'ParticlesLoadingView'

  # Pods for ExpertWorkBook

  target 'ExpertWorkBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpertWorkBookUITests' do
    # Pods for testing
  end

end
