# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'

  # Pods for Practice_2

  target 'Practice_2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Practice_2UITests' do
    # Pods for testing
  end

end
