# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpertWorkBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'lottie-ios'
  pod 'ParticlesLoadingView'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'KakaoSDK'
  pod 'Kingfisher', '~> 7.0'
  pod 'RealmSwift', '~>10'

  # Pods for ExpertWorkBook

  target 'ExpertWorkBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpertWorkBookUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end