# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice5-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'lottie-ios'

  # Pods for Practice5-2

end
